[package]
name = "bevy_rapier2d_despawn"
version = "0.1.0"
authors = ["Alia <alia.mccutcheon@gmail.com>"]
edition = "2018"

[profile.release.build-override]
opt-level = 3
debug = true

[dependencies]
bevy = "0.4.0" 
bevy_rapier2d = { version = "0.8.0", features = [ "simd-stable", "parallel" ] }

rust-hsluv = "0.1.4"